version: '3.4'

services:
  sql.identity:
    container_name: sql-identity
    environment:
      - POSTGRES_PASSWORD=${IDENTITY_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - sqldata-identity-store:/var/lib/postgresql/data \
    networks:
      - identitynet

  sql.school:
    container_name: sql.school
    environment:
      - MARIADB_ROOT_PASSWORD=${SCHOOL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - sqldata-school-store:/var/lib/mysql
    networks:
      - schoolnet

  sql.notesandmaths:
    container_name: sql.notesandmaths
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - sqldata-notesandmathsnet-store:/var/data

  queue.majorvillage:
    container_name: queue.majorvillage
    ports:
      - "15672:15672"
      - "5672:5672"
 
  school.api:
    container_name: school.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=${IDENTITYURL}
      - GRPC_PORT=81
      - ConnectionSchool=server=sql.school;user id=root;password=${SCHOOL_PASSWORD};database=SchoolDb
      - EncryptedKey=${ENCRYPTED_KEY}
      - ClientIdSchoolApi=
      - ClientSecretSchoolApi=
    ports:
      - "5108:81"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - identity.api
    networks:
      - identitynet
      - schoolgrpcnet

  notesandmaths.api:
    container_name: notesandmaths.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EncryptedKey=${ENCRYPTED_KEY}
    ports:
      - "5210:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  majorvillage.web:
    container_name: majorvillage.web
    ports:
      - "5305:80"

  majorvillage.admin:
    container_name: majorvillage.admin
    ports:
      - "5405:80"

  aggregator.web.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - GRPC_URL=http://school.api:81
      - EncryptedKey=${ENCRYPTED_KEY}
      - IdentityUrl=${IDENTITYURL}
    ports:
      - "5505:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    networks:
      - schoolgrpcnet
      
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SchoolApiClient=http://{DNS_OR_IP_HOST_CONTAINER}:5107
      - NoteAndMathsApi=http://{DNS_OR_IP_HOST_CONTAINER}:5210
      - ConnectionIdentity=host=sql.identity;port=5432;database=IdentityDb;username=postgres;password=${IDENTITY_PASSWORD}
      - IdentityUrl=${IDENTITYURL}
      - UrlsAllow=IdentityApi@5005,SchoolApi@5107,NoteAndMathsApi@5210,MajorWeb@5305,IdentityLogin@3000
      - EncryptedKey=${ENCRYPTED_KEY}
    ports:
      - "5005:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    networks:
      - identitynet

networks:
  identitynet:
    driver: bridge
  schoolnet:
    driver: bridge
  schoolgrpcnet:
    driver: bridge
  notesandmathsnet:
    driver: bridge

volumes:
  sqldata-identity-store:
    external: false
  sqldata-school-store:
    external: false
  sqldata-notesandmathsnet-store:
    external: false


