global using Xunit;
global using Moq;
global using Core.Interfaces;
global using Core.Services;
global using Core.Entities;
global using Core.Dtos;
global using Microsoft.Extensions.Logging;
global using System.Threading;
global using Api.EndPoints;