global using System;
global using System.ComponentModel.DataAnnotations;
global using System.Reflection;
global using System.Text.Json;
global using Ardalis.Specification;
global using AutoMapper;
global using BuildingBlock.Commons.Helpers;
global using BuildingBlock.Repository.Data;
global using BuildingBlock.Repository.Interfaces;
global using Google.Protobuf.Collections;
global using GrpcSchool;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using School.Core.Data;
global using School.Core.Entities;
global using School.Core.Interfaces;
global using School.Core.Repositories;
global using School.Core.Specifications;
global using Area = School.Core.Entities.Area;
global using ClassRoom = School.Core.Entities.ClassRoom;
global using School.Core.Helpers;

