global using System;
global using System.ComponentModel.DataAnnotations;
global using System.Reflection;
global using System.Text.Json;
global using Ardalis.Specification;
global using AutoMapper;
global using BuildingBlock.Commons.Helpers;
global using BuildingBlock.Repository.Data;
global using BuildingBlock.Repository.Interfaces;
global using Google.Protobuf.Collections;
global using GrpcSchool;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using School.Core.Data;
global using School.Core.Helpers;
global using School.Core.Interfaces;
global using School.Core.Repositories;
global using Area = School.Core.Entities.Area;
global using ClassRoom = School.Core.Entities.ClassRoom;
global using Course = School.Core.Entities.Course;
global using ElectiveYear = School.Core.Entities.ElectiveYear;
global using Enrollment = School.Core.Entities.Enrollment;
global using Period = School.Core.Entities.Period;
global using Student = School.Core.Entities.Student;
global using Subject = School.Core.Entities.Subject;
global using School.Core.Specifications;

